#!/bin/bash
screen -S mc -p 0 -X stuff "save-off\nsay Server Saving Disabled. Running Backup.\n"
d=$(date +%Y-%m-%d)
tar -cpvzf /opt/minecraft/Backups/TLHF2/TLHF2-$d.tar.gz /opt/minecraft/TLHF2
screen -S mc -p 0 -X stuff "save-on\nsay Serving Saving Enabled. Backup Complete! Restarting Server...\n"
sleep 5
/opt/minecraft/scripts/restartServer.sh
if cd /opt/minecraft/Backups/TLHF2/; then
        rm -fr "$(ls -t /opt/minecraft/Backups/TLHF2/ | tail -1)"
fi
